import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Plus, Minus, HelpCircle } from 'lucide-react'

export default function FAQ() {
  const faqs = [
    {
      q: 'How are reports generated?',
      a: 'Reports are generated by importing raw evaluation data (via CSV/Excel uploads or API endpoints) from your assessment source. ClearHire maps this data to a customized rubric and extracts strengths, growth areas, and learning paths without sharing code details.',
    },
    {
      q: 'Does ClearHire expose coding questions?',
      a: 'No. ClearHire protects coding questions, raw test cases, and hidden parameters. Candidates receive explanations of underlying concepts and rubric outcomes, ensuring your active assessment items remain secure.',
    },
    {
      q: 'Can recruiters customize evaluation criteria?',
      a: 'Yes. The Recruiter Dashboard includes a custom Rubric Builder where you can define specific skills (e.g., Coding Accuracy, System Design, CS Fundamentals), weights, and specify exactly which fields are visible to applicants.',
    },
    {
      q: 'Does ClearHire integrate with HackerRank or CodeSignal?',
      a: 'Yes. ClearHire 1.0 supports CSV and Excel reports from HackerRank, CodeSignal, Codility, and internal test suites. We are currently implementing direct API integrations for automated score syncs.',
    },
    {
      q: 'Is AI making hiring decisions?',
      a: 'No. ClearHire is a transparency layer. The hiring outcomes and scores are set by your team or testing platforms. The AI only explains the scores using the defined rubrics and generates study roadmaps for growth.',
    },
    {
      q: 'How is Hiring DNA generated?',
      a: 'Hiring DNA is generated from recruiter-provided evaluation rubrics combined with publicly available hiring information and aggregate candidate community insights. Official rubric fields are marked with verified badge labels.',
    },
    {
      q: 'What is the Transparency Score?',
      a: 'The Transparency Score™ measures the degree of info shared with candidates (rubric weights, timelines, AI feedback) while verifying that proprietary elements (question banks, internal rankings) are kept secure.',
    },
  ]

  const [activeIndex, setActiveIndex] = useState<number | null>(null)

  const toggleFAQ = (idx: number) => {
    setActiveIndex(activeIndex === idx ? null : idx)
  }

  return (
    <section id="faq" className="py-20 md:py-28 bg-zinc-50/50 dark:bg-zinc-900/10 border-y border-gray-100 dark:border-zinc-900/60 text-left">
      <div className="max-w-4xl mx-auto px-6 md:px-8">
        
        {/* Section Header */}
        <div className="text-center space-y-4 mb-16">
          <span className="text-xs font-bold uppercase tracking-wider text-accent px-3 py-1 rounded-full bg-accent/5 dark:bg-accent/10 border border-accent/10">
            Frictionless FAQ
          </span>
          <h2 className="text-3xl md:text-4xl font-display font-bold text-zinc-900 dark:text-white text-center">
            Frequently Asked Questions
          </h2>
          <p className="text-zinc-550 dark:text-zinc-400 max-w-xl mx-auto text-center">
            Learn how ClearHire maintains assessment privacy, structures candidate reports, and aggregates hiring trends.
          </p>
        </div>

        {/* Accordion List */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = activeIndex === idx
            return (
              <div
                key={idx}
                className="rounded-2xl border border-gray-200/60 dark:border-zinc-800/85 bg-white dark:bg-zinc-950/80 shadow-premium overflow-hidden transition-all duration-300 hover:border-primary/20"
              >
                <button
                  onClick={() => toggleFAQ(idx)}
                  className="w-full px-6 py-5 flex items-center justify-between text-left gap-4 font-semibold text-zinc-900 dark:text-white hover:text-primary dark:hover:text-primary transition-colors cursor-pointer"
                >
                  <span className="flex items-center gap-2.5 font-display text-sm md:text-base pr-4">
                    <HelpCircle className="w-4 h-4 text-primary flex-shrink-0" />
                    {faq.q}
                  </span>
                  <div className="w-6 h-6 rounded-lg bg-zinc-50 dark:bg-zinc-900 flex items-center justify-center flex-shrink-0">
                    {isOpen ? (
                      <Minus className="w-3.5 h-3.5 text-zinc-650 dark:text-zinc-400" />
                    ) : (
                      <Plus className="w-3.5 h-3.5 text-zinc-650 dark:text-zinc-400" />
                    )}
                  </div>
                </button>

                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: 'easeInOut' }}
                      className="overflow-hidden border-t border-gray-50 dark:border-zinc-900"
                    >
                      <p className="px-6 py-4 text-xs md:text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed bg-zinc-50/20 dark:bg-zinc-900/5">
                        {faq.a}
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            )
          })}
        </div>

      </div>
    </section>
  )
}
