"""add_external_assessment

Revision ID: 5d7558038769
Revises: 93df181707f0
Create Date: 2026-08-17 01:33:15.053638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7558038769'
down_revision: Union[str, Sequence[str], None] = '93df181707f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('assessment_name', sa.String(length=255), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('interview_questions', sa.JSON(), nullable=True),
    sa.Column('evaluation_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_external_assessments_id'), 'external_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_assessments_id'), table_name='external_assessments')
    op.drop_table('external_assessments')
    # ### end Alembic commands ###
