"""add_hiring_copilot_fields

Revision ID: acc2f426b41d
Revises: 032e93e2875d
Create Date: 2026-07-30 23:18:37.572632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc2f426b41d'
down_revision: Union[str, Sequence[str], None] = '032e93e2875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('hiring_notes', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('evaluation_rubric', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('rubric_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evaluations', sa.Column('match_percentage', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('evaluations', sa.Column('matched_skills', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('evaluations', sa.Column('missing_skills', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('evaluations', sa.Column('mandatory_requirements_met', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('evaluations', sa.Column('rubric_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'rubric_version')
    op.drop_column('evaluations', 'mandatory_requirements_met')
    op.drop_column('evaluations', 'missing_skills')
    op.drop_column('evaluations', 'matched_skills')
    op.drop_column('evaluations', 'match_percentage')
    op.drop_column('campaigns', 'rubric_generated_at')
    op.drop_column('campaigns', 'evaluation_rubric')
    op.drop_column('campaigns', 'hiring_notes')
    op.drop_column('campaigns', 'job_description')
    # ### end Alembic commands ###
