"""add candidate model

Revision ID: d42d34a4bd55
Revises: 4d7ef673fba4
Create Date: 2026-07-20 01:37:19.232535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42d34a4bd55'
down_revision: Union[str, Sequence[str], None] = '4d7ef673fba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_url', sa.String(length=500), nullable=True))
    op.drop_column('candidates', 'scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('candidates', 'resume_url')
    # ### end Alembic commands ###
